FROM python:3.13.3-slim

WORKDIR /app

COPY requirements-dev.txt .
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements-dev.txt

COPY . .

EXPOSE 8000
CMD ["flask", "run", "--host=0.0.0.0", "--port=8000", "--reload"]
